### ISSUE TITLE
Implement GitHub Actions CI - DockerHub Build

### ISSUE THREAD

**Issue by Kartstig** [mass-matrix/AMPL#6]
## Background
We will need a CI script to build and push AMPL Docker images. For certain releases we may want to tag accordingly. The first step here will be to setup CI, and then we can figure out tagging schemes at a later time. It looks like there is already some CI for tests https://github.com/mass-matrix/AMPL/blob/25fcc4c09ee58bbe6a968da2a4b8247d9d408397/.github/workflows/pkg_conda_pytest_unit.yml

## Open Questions
- Where will the images be hosted?
  - ~~AWS ECR~~
  - DockerHub
- How should images be tagged?
Certain branches may need to be released
For now I will just use an `ENV` variable to determine the release. We can add versions and other tracking items later

**Comment by joverhul** [comment]
@Kartstig The images will be hosted in DockerHub.

**Comment by Kartstig** [comment]
I was able to get the previous ~12GB gpu build down to 7.5GB

![Image](https://github.com/mass-matrix/AMPL/assets/2031422/dc341002-710a-4ec6-89ab-22106b9be901)

I am going to create a separate issue ticket to handle pushing to fnl docker hub. If we are going to use CI, then I will assume we will create some credential for login purposes. For now I have a variable `IMAGE_REPO` to build to a particular repository:

```bash
herman@carnage ⏎  PLATFORM=gpu IMAGE_REPO=kartstig/ampl make push-docker
docker push kartstig/ampl:gpu-dev
The push refers to repository [docker.io/kartstig/ampl]
c4babd407797: Pushed 
f1c97370f9db: Pushed 
a747a7d710b4: Pushed 
2b0b386e50df: Pushed 
fe3645e2cb27: Layer already exists 
80efa168fd62: Layer already exists 
f59f1628a120: Layer already exists 
12415aea094b: Layer already exists 
b9ea3813055b: Pushed 
b289449e2f7e: Pushed 
294d01ebb8e6: Layer already exists 
8963f4351b31: Pushed 
85ee822ae89c: Pushed 
50592bbead19: Pushed 
bbb185393d00: Pushed 
07a6aadd26ef: Layer already exists 
64a71ff38e88: Layer already exists 
5bf332827eb6: Layer already exists 
cbe4fb5e267b: Layer already exists 
734c0f0b65c2: Layer already exists 
8845ab872c1c: Layer already exists 
d7d4c2f9d26b: Layer already exists 
bbe1a212f7e9: Layer already exists 
gpu-dev: digest: sha256:1c73cf690819da2b1807b34be4bbc879e755a241f52720c77fdad0d5eae1f047 size: 5143
```

Also note that I used `PLATFORM` to specify whether you want a cpu or gpu build
